[package]
name = "tt"
version = "0.1.0"
authors = ["Nick Yasinskiy <1@shfu.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0.1"
